version: "3.7"

services:
  forticlient:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VPNADDR=host:port
      - VPNUSER=me@domain
      - VPNPASS=secret
      - VPNTIMEOUT=10
    network_mode: "host"
    privileged: true
