#!/usr/bin/expect -f

set timeout $env(VPNTIMEOUT)

spawn "/usr/share/forticlient/opt/forticlient-sslvpn/64bit/forticlientsslvpn_cli" --server $env(VPNADDR) --vpnuser $env(VPNUSER) --keepalive

# Send command
expect -exact "Password for VPN:"
send -- "$env(VPNPASS)\n"

expect -exact "STATUS::Connecting..."

while { true } {
  expect {
    # In case of invalid certificate
    "Would you like to connect to this server? (Y/N)" {
  	  send -- "Y\n"
    }
    # In case a token is needed
    "A FortiToken code is required for SSL-VPN login authentication." {
      # Clear previos token (if any)
  	  exec echo "" > /vpntoken.txt
  	  # Count words in /vpntoken.txt
  	  set wc [exec cat /vpntoken.txt | wc -w]
  	  while {$wc == 0} {
  	    send_user -- "VPN Token not defined yet in /vpntoken.txt\n"
  	  	exec sleep 1
  	  	set wc [exec cat /vpntoken.txt | wc -w]
  	  }
  	  set vpntoken [exec cat /vpntoken.txt]
  	  send -- "$vpntoken\n"
    }
    # Expect tunnel to actually start
    "STATUS::Tunnel running" {
      break
    } timeout {
      send_user -- "Failed to bring tunnel up after $env(VPNTIMEOUT)s\n"
      exit 1
    }
  }
}

# Expect tunnel to stop but not exit
set timeout -1
expect {
  "STATUS::Tunnel closed" {
    exit 1
  }
  eof {
    exit
  }
}
